# Übung 2

In [171]:
import numpy as np
from numpy.linalg import inv

### Load the different training sets and prepare training sets for the various matchups

In [172]:
trainlist = []
trainsets = ['train3','train5','train7','train8']
for trainset in trainsets:
    trainlist.append(np.loadtxt(trainset,delimiter=','))
    
### set with 3 and 5
left = np.concatenate(((np.full((trainlist[0].shape[0],1),1)),trainlist[0]),axis=1)
right = np.concatenate(((np.full((trainlist[1].shape[0],1),-1)),trainlist[1]),axis=1)
threefive = np.concatenate((left,right),axis=0)

### set with 3 and 7
left = np.concatenate(((np.full((trainlist[0].shape[0],1),1)),trainlist[0]),axis=1)
right = np.concatenate(((np.full((trainlist[2].shape[0],1),-1)),trainlist[2]),axis=1)
threeseven = np.concatenate((left,right),axis=0)

### set with 3 and 8
left = np.concatenate(((np.full((trainlist[0].shape[0],1),1)),trainlist[0]),axis=1)
right = np.concatenate(((np.full((trainlist[3].shape[0],1),-1)),trainlist[3]),axis=1)
threeeight = np.concatenate((left,right),axis=0)

### set with 5 and 7
left = np.concatenate(((np.full((trainlist[1].shape[0],1),1)),trainlist[1]),axis=1)
right = np.concatenate(((np.full((trainlist[2].shape[0],1),-1)),trainlist[2]),axis=1)
fiveseven = np.concatenate((left,right),axis=0)

### set with 5 and 8
left = np.concatenate(((np.full((trainlist[1].shape[0],1),1)),trainlist[1]),axis=1)
right = np.concatenate(((np.full((trainlist[3].shape[0],1),-1)),trainlist[3]),axis=1)
fiveeight = np.concatenate((left,right),axis=0)

### set with 7 and 8
left = np.concatenate(((np.full((trainlist[2].shape[0],1),1)),trainlist[2]),axis=1)
right = np.concatenate(((np.full((trainlist[3].shape[0],1),-1)),trainlist[3]),axis=1)
seveneight = np.concatenate((left,right),axis=0)

### Load the test set and prepare test sets for the various matchups

In [173]:
testset = np.loadtxt('zip.test')

testlist = []
totest = [3,5,7,8]

for i in totest:
    testlist.append(testset[testset[:,0] == i])
    
### set with 3 and 5
left = np.concatenate(((np.full((testlist[0].shape[0],1),1)),testlist[0][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[1].shape[0],1),-1)),testlist[1][:,1:]),axis=1)
threefive_test = np.concatenate((left,right),axis=0)

### set with 3 and 7
left = np.concatenate(((np.full((testlist[0].shape[0],1),1)),testlist[0][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[2].shape[0],1),-1)),testlist[2][:,1:]),axis=1)
threeseven_test = np.concatenate((left,right),axis=0)

### set with 3 and 8
left = np.concatenate(((np.full((testlist[0].shape[0],1),1)),testlist[0][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[3].shape[0],1),-1)),testlist[3][:,1:]),axis=1)
threeeight_test = np.concatenate((left,right),axis=0)

### set with 5 and 7
left = np.concatenate(((np.full((testlist[1].shape[0],1),1)),testlist[1][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[2].shape[0],1),-1)),testlist[2][:,1:]),axis=1)
fiveseven_test = np.concatenate((left,right),axis=0)

### set with 5 and 8
left = np.concatenate(((np.full((testlist[1].shape[0],1),1)),testlist[1][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[3].shape[0],1),-1)),testlist[3][:,1:]),axis=1)
fiveeight_test = np.concatenate((left,right),axis=0)

### set with 7 and 8
left = np.concatenate(((np.full((testlist[2].shape[0],1),1)),testlist[2][:,1:]),axis=1)
right = np.concatenate(((np.full((testlist[3].shape[0],1),-1)),testlist[3][:,1:]),axis=1)
seveneight_test = np.concatenate((left,right),axis=0)

In [174]:
trainlist[2]

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ..., 
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [175]:
class LinearRegression:
    
    def __init__(self):
        pass
    
    def train(self,array):
        """takes training set and splits into X (data) and y (labels)"""
        self.X = array[:,1:]
        self.y = array[:,0]
        self.beta = self.compute_beta()
        
    def pinv(self, X, increment=0.05):
        """attempts to invert a matrix, if not possible, then it tries again with a refactored matrix"""
        I = np.eye(X.shape[0])
        my_lambda = 0
        X1 = X
        while True:
            try:
                inv(X1)
                break
            except np.linalg.LinAlgError:
                my_lambda += increment
                X1 = np.add(X, np.multiply(I,my_lambda))
        return inv(X1)
        
    def bigX(self,X):
        """returns array with first column filled with ones, and the rest filled with data from X"""
        justones = np.ones((1,X.shape[0]))
        result = np.concatenate((justones.T,X),axis=1)
        return result
    
    def covariance_matrix(self,X):
        """returns the covariance matrix of X"""
        return np.dot(X.T,X)
    
    def compute_beta(self):
        """finds beta given the training set and the label k to be tested"""
        X1 = np.dot(self.pinv(self.covariance_matrix(self.bigX(self.X))),self.bigX(self.X).T)
        return np.dot(X1,self.y)
    
    def changelabels(self,arrtochange):
        """in labels, changes all positive numbers to 0s and all negative numbers to 1s"""
        result = np.zeros((arrtochange.size))
        for i in range(0,arrtochange.size):
            if arrtochange[i] >= 0:
                result[i] = 0
            else:
                result[i] = 1
        return result
    
    def predict(self,testset):
        """classifier for exactly two classes, gives values between -1 and +1"""
        self.X_test = self.bigX(testset[:,1:])
        self.y_test = testset[:,0]
        self.prediction = np.sum(np.multiply(self.beta.T,self.X_test),axis=1)
        return self.prediction
    
    def error_rate(self):
        pred = self.changelabels(self.prediction)
        testlabels = self.y_test
        datacount = pred.shape[0]
        bools = np.equal(self.changelabels(testlabels),pred.flatten())
        correct = np.sum(bools)
        return (datacount-correct)/datacount
        #return pred
    
    def confusion_matrix(self):
        preds = self.changelabels(self.prediction).flatten()
        testlabels = self.y_test
        changedtestlabels = self.changelabels(testlabels)
        size = testlabels.size
        mtrx = np.zeros((2,2))
        for i in range(0,size):
            mtrx[int(changedtestlabels[i]),int(preds[i])] += 1
        return mtrx

### 3 vs 5

In [176]:
linreg35 = LinearRegression()

In [177]:
linreg35.train(threefive)

In [178]:
linreg35.predict(threefive_test)

array([ 1.54406208,  0.92049329, -0.42360194,  0.48262751,  1.25552788,
        0.92542761,  0.71750693,  0.93516691, -0.0262136 ,  0.95320363,
        1.39713988,  1.04896973,  0.69698686,  0.71072516,  0.81583961,
        1.42595604,  1.03675658,  1.33090697,  0.66553801,  0.68894959,
        1.14923176,  0.79343849,  0.98374933,  1.41485031, -0.56333768,
        0.80016713,  1.67705315,  0.94417203,  0.09325294, -0.0754336 ,
        0.90990917,  1.18325106,  0.15100695,  0.44369413,  0.84956316,
        1.32101577,  1.05863859,  1.39660494,  1.3595713 ,  0.8612351 ,
        1.18395464,  1.21275156,  1.10959977,  0.67920989,  0.29286056,
        1.37115586, -0.05187408,  1.12595201,  0.61861106,  0.93621186,
        1.06627908,  0.75579275,  0.95087799,  0.94019287,  0.98851092,
       -0.05888806,  0.23273467,  0.19609524,  0.84284554,  1.01776305,
        0.61010164,  0.20101837,  1.1697076 ,  0.82725932,  0.76592056,
        0.97019442,  0.68218666,  1.36241163,  0.57704762,  0.91

In [188]:
print("3 vs 5 error rate = "+str(linreg35.error_rate()))

3 vs 5 error rate = 0.0705521472393


In [180]:
linreg35.confusion_matrix().astype('uint16')

array([[154,  12],
       [ 11, 149]], dtype=uint16)

### 3 vs 7

In [181]:
linreg37 = LinearRegression()
linreg37.train(threeseven)
linreg37.predict(threeseven_test)
print("3 vs 7 error rate = "+str(linreg37.error_rate()))
linreg37.confusion_matrix().astype('uint16')

3 vs 7 error rate = 0.0255591054313


array([[161,   5],
       [  3, 144]], dtype=uint16)

### 3 vs 8

In [182]:
linreg38 = LinearRegression()
linreg38.train(threeeight)
linreg38.predict(threeeight_test)
print("3 vs 8 error rate = "+str(linreg38.error_rate()))
linreg38.confusion_matrix().astype('uint16')

3 vs 8 error rate = 0.0481927710843


array([[156,  10],
       [  6, 160]], dtype=uint16)

### 5 vs 7

In [183]:
linreg57 = LinearRegression()
linreg57.train(fiveseven)
linreg57.predict(fiveseven_test)
print("5 vs 7 error rate = "+str(linreg57.error_rate()))
linreg57.confusion_matrix().astype('uint16')

5 vs 7 error rate = 0.0162866449511


array([[157,   3],
       [  2, 145]], dtype=uint16)

### 5 vs 8

In [184]:
linreg58 = LinearRegression()
linreg58.train(fiveeight)
linreg58.predict(fiveeight_test)
print("5 vs 8 error rate = "+str(linreg58.error_rate()))
linreg58.confusion_matrix().astype('uint16')

5 vs 8 error rate = 0.0368098159509


array([[154,   6],
       [  6, 160]], dtype=uint16)

### 7 vs 8

In [189]:
linreg78 = LinearRegression()
linreg78.train(seveneight)
linreg78.predict(seveneight_test)

array([ -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,  -7.20001775e+12,  -7.20001775e+12,
        -7.20001775e+12,

In [190]:
print("7 vs 8 error rate = "+str(linreg78.error_rate()))
linreg78.confusion_matrix().astype('uint16')

7 vs 8 error rate = 0.4696485623


array([[  0, 147],
       [  0, 166]], dtype=uint16)

In [193]:
linreg78.X_test

array([[ 1.  , -1.  , -0.99, ..., -1.  , -1.  , -1.  ],
       [ 1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ],
       [ 1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ],
       ..., 
       [ 1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ],
       [ 1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ],
       [ 1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ]])

In [195]:
linreg78.beta

array([  1.88522221e+12,   4.90349388e+00,   2.11481094e-01,
         1.09245276e+00,  -1.20181179e+00,  -2.76487827e-01,
        -8.82860184e-01,   3.42567205e-01,  -3.19647789e-02,
        -4.64088917e-01,   5.79541206e-01,   3.14281225e-01,
        -4.03476834e-01,   1.93474293e-02,  -2.01158953e+00,
         4.20689067e+00,   1.09451294e-01,   3.73510551e+00,
        -2.45831108e+00,  -1.19540811e+00,   1.00441612e+00,
        -7.78157711e-01,   6.57642841e-01,  -1.34083748e-01,
        -5.36391258e-01,   5.09827614e-01,   6.12923265e-01,
        -1.98415160e-01,  -9.91716385e-02,   7.60674864e-01,
         1.32424355e-01,   3.23411465e+00,  -7.53496170e+00,
         5.07468987e+00,  -2.11765289e-01,   9.28371429e-01,
        -5.66558897e-01,   1.85893178e-01,  -1.67411804e+00,
         1.27623415e+00,  -1.53875446e+00,   9.45503920e-01,
        -4.70651150e-01,  -9.42289829e-02,   8.16849232e-01,
        -9.15844440e-02,   1.81497574e-01,   2.62324333e-01,
        -3.40205002e+00,